version: '3.8'

services:
  app:
    # 使用するイメージが存在しない場合、ビルドする
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # ソースコードをコンテナ内にマウント（変更をコンテナ内で反映）
      - .:/app
      # 認証情報をコンテナに渡す
      - ~/.aws/:/root/.aws
    ports:
      - "8080:8080"
    command: ["./myapp"]  # 実行するコマンド（Goバイナリ）
    environment:
      - GO111MODULE=on
    # ホットリロードツール 'air' を使う場合は、以下を追加
    depends_on:
      - air
    # TODO:ホットリロードうまくいってないのでどこかでチェック
    develop:
      watch:
        - action: sync
          paths: .

  air:
    image: cosmtrek/air  # airツールの公式Dockerイメージ
    volumes:
      - .:/app  # ソースコードをマウント
    working_dir: /app
    command: air
    environment:
      - AIR_WATCH_DIR=/app
    # air用の設定を追加
    entrypoint: ["air", "-c", "/app/.air.toml"]  # airの設定ファイル（.air.toml）を指定

  super-linter:
    image: ghcr.io/super-linter/super-linter:slim-v5
    environment:
      RUN_LOCAL: 'true'
      MULTI_STATUS: 'false'
      VALIDATE_ALL_CODEBASE: 'true'
      # Terraform と Markdown のみを有効化
      VALIDATE_TERRAFORM_TFLINT: 'true'
      VALIDATE_TERRAFORM_TERRASCAN: 'true'
      VALIDATE_MARKDOWN: 'true'
      # キャッシュを有効化して実行速度を向上
      USE_FIND_ALGORITHM: 'true'
      DEFAULT_BRANCH: 'main' # デフォルトのブランチを指定 master -> mainに変更
      DISABLE_ERRORS: 'true'  # レポート出力を抑制
      LOG_LEVEL: 'ERROR'  # ログレベルを ERROR に設定
      LOG_VERBOSE: 'false'  # 詳細なログを無効化
    volumes:
      - .:/tmp/lint
    working_dir: /tmp/lint
