version: '3.8'
services:
  app:
    build:
      context: .  # ここは現在のディレクトリ（つまりプロジェクトルート）を指している
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
